name: CI

on:
  pull_request:
    branches: ["*"]

# Define permissions at workflow level with enhanced access
permissions:
  contents: read
  pull-requests: write # Upgraded from read to write to post status comments
  checks: write # Added to create check runs
  actions: read # Added to read workflow runs
  security-events: write # Added for security scanning

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
